export const GET_CHALLENGES_REQUEST = "GET_CHALLENGES_REQUEST";
export const GET_CHALLENGES_SUCCESS = "GET_CHALLENGES_SUCCESS";
export const GET_CHALLENGES_ERROR = "GET_CHALLENGES_ERROR";
export const GET_CHALLENGE_DETAILS_REQUEST = "GET_CHALLENGE_DETAILS_REQUEST";
export const GET_CHALLENGE_DETAILS_SUCCESS = "GET_CHALLENGE_DETAILS_SUCCESS";
export const GET_CHALLENGE_DETAILS_ERROR = "GET_CHALLENGE_DETAILS_ERROR";
