export const GETME_REQUEST = "GETME_REQUEST";
export const GETME_SUCCESS = "GETME_SUCCESS";
export const GETME_ERROR = "GETME_ERROR";
export const GETME_RESET="GETME_RESET"
export const CHANGEAVATAR_REQUEST = "CHANGEAVATAR_REQUEST";
export const CHANGEAVATAR_SUCCESS = "CHANGEAVATAR_SUCCESS";
export const CHANGEAVATAR_ERROR = "CHANGEAVATAR_ERROR";

export const CHANGEUSERNAME_REQUEST="CHANGEUSERNAME_REQUEST"
export const CHANGEUSERNAME_SUCCESS="CHANGEUSERNAME_SUCCESS"
export const CHANGEUSERNAME_ERROR="CHANGEUSERNAME_ERROR"

export const SETQUESTION_REQUEST="SETQUESTION_REQUEST"
export const SETQUESTION_SUCCESS="SETQUESTION_SUCCESS"
export const SETQUESTION_ERROR="SETQUESTION_ERROR"